services:
    dockerize-modular-monolith:
        build:
            context: .
            dockerfile: src/ModularMonolith/Dockerfile
        image: modular-monolith:latest
        container_name: modular-monolith-app
        ports:
            - ${APP_PORT}:8080
        depends_on:    
            modular-monolith-db:
                condition: service_healthy
            jaeger:
                condition: service_healthy
        restart: unless-stopped
    
    modular-monolith-db:
        image: postgres:16-alpine
        container_name: modular-monolith-postgres
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
          - ${DB_PORT}:5432
        volumes:
          - modular-monolith-db-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
            interval: 10s
            timeout: 5s
            retries: 3
   

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: modular-monolith-pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        ports:
            - ${PGADMIN_PORT}:80
        volumes:
           - modular-monolith-pgadmin-data:/var/lib/pgadmin
        depends_on:
            modular-monolith-db:
                condition: service_healthy
        restart: always

    jaeger:
        image: jaegertracing/all-in-one:latest
        container_name: modular-monolith-jaeger
        environment:
            COLLECTOR_OTLP_ENABLED: "true"

        ports:
            - "${JAEGER_UI_PORT}:16686"   
            - "${JAEGER_OTLP_GRPC_PORT}:4317"     
            - "${JAEGER_OTLP_HTTP_PORT}:4318"     
        volumes:
            - modular-monolith-jaeger-data:/data
        restart: unless-stopped

volumes:
    modular-monolith-db-data:
    modular-monolith-pgadmin-data:
    modular-monolith-jaeger-data:
    