apiVersion: v1
kind: ConfigMap
metadata:
  name: modular-monolith-config
  namespace: modular-monolith-system
  labels:
    app.kubernetes.io/name: modular-monolith
    app.kubernetes.io/component: config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft.AspNetCore: "Warning"
  Logging__LogLevel__Microsoft.EntityFrameworkCore: "Warning"
  Jaeger__Endpoint: "http://modular-monolith-jaeger:4317"
  Email__Host: "smtp.gmail.com"
  Email__Port: "587"
  Email__FromEmail: "alihancelik7140@gmail.com"
  Email__EnableSsl: "true"
